#!/usr/bin/env bash
# Read 
while IFS=':' read -r username _ uid _ _ _ homedir _; do
  echo "Username: $username"
  echo "User ID: $uid"
  echo "Home Directory: $homedir"
  echo "-----------------------"
done < /etc/passwd

